-- MySQL Script generated by MySQL Workbench
-- 04/29/14 09:44:20
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `NomeEvento` VARCHAR(60) NOT NULL,
  `PalestranteEvento` VARCHAR(80) NOT NULL,
  `DataEvento` DATETIME NULL,
  PRIMARY KEY (`idEvento`),
  UNIQUE INDEX `idEventos_UNIQUE` (`idEvento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `idAluno` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `NomeAluno` VARCHAR(80) NULL,
  `MatriculaAluno` VARCHAR(7) NULL,
  `SenhaAluno` VARCHAR(64) NULL,
  `EmailAluno` VARCHAR(100) NULL,
  `Salt` VARCHAR(6) NULL,
  PRIMARY KEY (`idAluno`),
  UNIQUE INDEX `idAluno_UNIQUE` (`idAluno` ASC),
  UNIQUE INDEX `MatriculaAluno_UNIQUE` (`MatriculaAluno` ASC),
  UNIQUE INDEX `EmailAluno_UNIQUE` (`EmailAluno` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento_has_Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento_has_Aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento_has_Aluno` (
  `Evento_idEvento` MEDIUMINT NOT NULL,
  `Aluno_idAluno` MEDIUMINT NOT NULL,
  PRIMARY KEY (`Evento_idEvento`, `Aluno_idAluno`),
  INDEX `fk_Evento_has_Aluno_Aluno1_idx` (`Aluno_idAluno` ASC),
  INDEX `fk_Evento_has_Aluno_Evento_idx` (`Evento_idEvento` ASC),
  CONSTRAINT `fk_Evento_has_Aluno_Evento`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
